### ISSUE TITLE
How to Retry produce message after creating topic

### ISSUE THREAD

**Issue by snober** [IBM/sarama#1628]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.22.1 | 2.4 | 1.12.9 |

##### Configuration

kafkaConfig.Metadata.Retry.Max = 5 
kafkaConfig.Producer.Retry.Max = 5
- Automatic topic creation is disabled in kafka

##### Problem Description
For new topic, sending message to kafka will fail, since automatic topic creation is disabled in kafka.
On Error of  **ErrUnknownTopicOrPartition** , API will be called to create the topic. How to retry sending the failed message, after creating the topic.

**Comment by cheesedosa** [comment]
Can you post a sample?

Why can't you orchestrate to resend the message? For sync producers, the error is returned immediately, so you can retry after your topic create API call succeeds. 
For async producers, the errors are returned on an `Errors()` channel. This `ProducerError (error)` contains the 
`ProducerMessage` that caused the error which you can then orchestrate to resend after the topic creation API succeeds.
If new topics get created frequently, I would recommend doing the creation preemptively instead of  on errors.
