### ISSUE TITLE
Multi-Topic Consumer Co-partitioning?

### ISSUE THREAD

**Issue by wood-jp** [IBM/sarama#1641]
When setting up a single consumer for multiple topics, are the partitions assigned co-partitioned? Is that an option?

Obviously, if the topics don't have the same partition count, this isn't possible. However if they are, there could be a lot of value in ensuring each instance of the consumer group is consuming the same set of partitions at any given time.

**Comment by wood-jp** [comment]
Please don't go stale. Just a simple question.

**Comment by dnwe** [comment]
@wood-jp firstly, apologies that your issue was overlooked for so long

However, It's not clear from the description what you were looking for in terms of "co-partitioning" if you only have a single consumer running? Did you actually mean co-partitioning on a consumer-group that has multiple clients consuming from multiple topics, to have each client assigned the same numerical partition from each topic?

**Comment by wood-jp** [comment]
Hi @dnwe, yes that is exactly what I meant: co-partitioning on a consumer-group that has multiple clients consuming from multiple topics, to have each client assigned the same numerical partition from each topic.

The use case was to have an efficient way to join the topics. Ultimately we were able to do this by consuming from one topic, then for each partition the client was assigned we then started another consumer only on that partition manually. It's been a while, so the details are fuzzy now and I no longer work at the company where I did this. It mostly worked out since the second topic was compacted and we only intended to read the entirety of the partition into memory.
