### ISSUE TITLE
Is it possible to use SASL with delegation token?

### ISSUE THREAD

**Issue by andrelu** [IBM/sarama#1648]
Hello everyone,

i'm trying to configure SASL with delegation token (https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_delegation.html#) on the client, but i could not figure out how to do it. Is it supported by sarama? If it is, can someone give me a hint how to do it?

i'm using sarama v1.26.1

**Comment by Chrisss93** [comment]
Well, might as well answer this for posterity, even if it's 3 years old 😆.  The short answer is yes, it is possible, but it's a PITA.  Kafka's delegation token authentication relies on basically abusing the SCRAM protocol in such a way where libraries implementing the standard SCRAM protocol (like xdg-go/scram) won't work and need to be re-implemented.

In `sarama.Config.Net.SASL.SCRAMClientGeneratorFun`, instead of supplying an implementation of `sarama.SCRAMClient` which just wraps functionality of `xdg-go/scram`'s `scram.Client` and `scram.ClientConversation` (i.e. [the repo example](https://github.com/IBM/sarama/blob/main/examples/sasl_scram_client/scram_client.go), you need to re-implement its SCRAM conversation such that the first client message is appended with `,tokenauth=true`, and also make sure that appended client message is used to create the client proof when responding to the first server message.

It's annoying, but it does work.
