### ISSUE TITLE
Question: producers not blancing over newly added partitions

### ISSUE THREAD

**Issue by KevinJCross** [IBM/sarama#1673]
Is there some work that the producer needs to do when new partions are added to balance over the new partitions added  to the topic while the producer is operating?

Currently if the producer is connected it will always keep the current partitions when it started and if I add a new partition it does not start balancing over the new partitions in the topic.
Is this known or is there some work in the producer code needed to start balancing over new partitions ?

I think this is the same with consumers. Im guessing the workaround is to force a new rebalance on a consumer group?

**Comment by nikolaydimitrov** [comment]
I was going to create a new issue but found this one. In my case the issue is with group consumers (might need a separate issue for this?)

I think if you wait for 10mins (default value for `Config.Metadata.RefreshFrequency`), the consumers will balance out. Actually I found that it needs sometimes two iterations to balance properly.

But the actual problem is that until that re-balance happens, messages sent to new partitions are basically lost for the given consumer group.
