### ISSUE TITLE
PartitionConsumer.Close() behavior mismatch

### ISSUE THREAD

**Issue by greysond** [IBM/sarama#1703]
Apologies if I'm misreading this, but in the docs for the PartitionConsumer, it states that the `Close()` method will "initiate a shutdown just like AsyncClose, drain the Messages channel, harvest any errors & return them to the caller."

I'm looking at the method [here](https://github.com/Shopify/sarama/blob/8b91b872756c4220f47cc69f2e115a4641908446/consumer.go#L422-L434) and it doesn't seem to be draining the messages channel.

**Comment by greysond** [comment]
I can definitely open a PR for this, but I just wanted to make sure I wasn't missing something.

**Comment by kjgorman** [comment]
This behaviour was removed in https://github.com/Shopify/sarama/pull/1156 — probably the godoc is just stale.

**Comment by harshana-pickme** [comment]
> This behaviour was removed in #1156 — probably the godoc is just stale.

What is the behaviour now? I'm using 1.27.2,  Here's what I observe

1. create a PartitionConsumer in one goroutine.
2. Before it starts reading the input channel, another goroutine call PartitionConsumer.Close() (due to quick rebalancing of another group consumer)
3. When the first goroutine reaches the channel reading "for" loop, I'm expecting it to terminate (before or after reading the channel) as the ParitionConsumer is now closed. But it does not terminate or read from channel. It gets stuck there forever.

Please enlighten us on this behaviour. 
How can I close the channel after closing the PartitionConsumer ?
