### ISSUE TITLE
How to read metadata,  previously set using ConsumerGroupSession.MarkOffset()

### ISSUE THREAD

**Issue by harshana-pickme** [IBM/sarama#1748]
##### Problem Description
Dear all,

Can someone let me know how to read metadata which was set using ConsumerGroupSession.MarkOffset() ? I need to do this to recovery purpose. 

Thank you,
Harshana

**Comment by harshana-pickme** [comment]
@dnwe can you please help me ?

**Comment by harshana-pickme** [comment]
This seem to be obvious, but I was not able to find a way to do this. Please help me.

**Comment by harshana-pickme** [comment]
Is this part still under development. Can someone please comment ?

**Comment by dnwe** [comment]
I’m not sure what you plan to use it for, but`NextOffset()` will return you the last offset you marked and the metadata string

**Comment by mark-rushakoff** [comment]
I'm in the same situation. I am configuring a `ConsumerGroup` using [`NewConsumerGroup`](https://pkg.go.dev/github.com/Shopify/sarama#NewConsumerGroup), so I have defined a [`ConsumerGroupHandler`](https://pkg.go.dev/github.com/Shopify/sarama#ConsumerGroupHandler).

Inside my handler, I have access to a [`ConsumerGroupSession`](https://pkg.go.dev/github.com/Shopify/sarama#ConsumerGroupSession) where I can call `MarkOffset` and set some metadata, and in the `ConsumeClaim` method, I have access to a [`ConsumerGroupClaim`](https://pkg.go.dev/github.com/Shopify/sarama#ConsumerGroupClaim). 

Inside the definition of  `(*consumerGroupSession).consume`, there is [`offset, _ = pom.NextOffset()`](https://github.com/Shopify/sarama/blob/83d633e6e4f71b402df5e9c53ad5c1c334b7065d/consumer_group.go#L663) which is explicitly discarding the metadata from the PartitionOffsetManager.

So, it looks like callers of `NewConsumerGroup` have to a roundabout way to retrieve the metadata for marked offsets:

1. Don't call `NewConsumerGroup` -- call `NewConsumerGroupFromClient`, because you're going to need that `Client` later.
2. Call `NewOffsetManagerFromClient` with the same `groupID` and `client` that you used for `NewConsumerGroupFromClient`.
3. At the beginning of your `ConsumerGroupHandler.ConsumeClaim` definition, use the `ConsumerGroupClaim` to access the appropriate [`PartitionOffsetManager`](https://pkg.go.dev/github.com/Shopify/sarama#PartitionOffsetManager) from your `OffsetManager`.
4. Finally, call `PartitionOffsetManager.NextOffset` to access the previously set offset and metadata.

(I haven't implemented this workflow yet, but that is what I've concluded from reading through the code.)

Ideally there would be a simpler way to just get the offset metadata inside a `ConsumerGroupHandler` without managing a separate `Client` and `OffsetManager`.

**Comment by Kaushal28** [comment]
> I’m not sure what you plan to use it for, but`NextOffset()` will return you the last offset you marked and the metadata string

@dnwe How would I call `NextOffset()`? It's defined on `PartitionOffsetManager` and there is no way I can access that object using `OffsetManager`. `OffsetManager` has `ManagePartition()` method but I don't think it'll always work since `It will return an error if this OffsetManager is already managing the given topic/partition.`

If this is the case, setting metadata on commit message is useless.
