### ISSUE TITLE
No way to determine if topic exist without iterating through entire Topics() list

### ISSUE THREAD

**Issue by llamahunter** [IBM/sarama#1890]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.26.4 | 2.4.0 | 1.12 |

##### Configuration

N/A

##### Logs

N/A

##### Problem Description

There appears to be no way in the API to determine if a topic exists in the metadata without an O(n) linear search through the entire array returned from Topics().  This is sad, because the internal metadata cache has topic information in an O(1) map. Trying to determine topic existence by Partitions() leads to unknown topics getting accidentally created with default attributes due to https://github.com/Shopify/sarama/issues/1889.

If the number of topics in the cluster is very large, the current implementation leads to unnecessary inefficiency, either with lots of O(n) calls, or reconstructing yet another topic name mapping cache above sarama.

**Comment by dnwe** [comment]
As you suggest, It should be safe to use `.Partitions(topicName)` for this check since v1.30 by setting the AllowAutoTopicCreation bool to false in config

https://github.com/IBM/sarama/blob/6162a43366a77ffca2ffec774e51127f8bf223ec/config.go#L164-L167

Does that satisfy the requirement or do you think we should do more here?
