### ISSUE TITLE
API to get active and pending subscriptions?

### ISSUE THREAD

**Issue by alok87** [IBM/sarama#1904]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.2 |  2.6| 1.16 |

##### Problem Description
https://github.com/Shopify/sarama/blob/master/consumer.go#L853-L857
```go
switch result {
case errTimedOut:
	Logger.Printf("consumer/broker/%d abandoned subscription to %s/%d because consuming was taking too long\n",
		bc.broker.ID(), child.topic, child.partition)
	delete(bc.subscriptions, child)
```

Subscription is abandoned if the MaxProcessingTime is not right. What happens here, is the processing get stuck for this topic as the session is still open and only this topic is not subscribed. 

In this case the user needs to know if this has happened and needs to take action for the subscription to happen. We are at present monitoring replica lag, then changing maxProcessingTime and recreating the process to fix it.

How can we get the list of active subscription (also pending) ? or get info about abandoning subscription, so that we automate this... (as sometimes maxProcessingTime is not same, it changes with time).

Please suggest.

**Comment by dnwe** [comment]
@alok87 I'm not sure I understand. Whenever a subscription is "abandoned" by the broker consumer, the partition consumer (that comprises the subscription) will dispatch itself (after some backoff) back to the preferred broker again and will resume processing again.

Are you saying that you're hitting an endless loop of re-dispatching and abandonment because your MaxProcessingTime is too low and you need to "know" that you should manually increase that configuration parameter?
