### ISSUE TITLE
How to detect session commit failure?

### ISSUE THREAD

**Issue by wjw1758548031** [IBM/sarama#1906]
session.MarkMessage(message, "")
session.ResetOffset(message.Topic,message.Partition,message.Offset,"")
session.Commit()

All failed. Kafka did not modify the offset value, or the previous offset value.
Why is this? or is there any way to fix it

**Comment by dnwe** [comment]
Yes, one area for improvement in a v2 API is within the offset commit flows. Currently the (manual) 'Commit' call is just a fire and forget func and any actual errors from the commit itself are flowed back onto the Consumer's errors channel (assuming `Consumer.Return.Errors` config setting is `true`), rather than being returned from the Commit call itself — so it is more like a "flush"

https://github.com/IBM/sarama/blob/a4eafb450c57b9a0243dc51f4cb9116f1f1bedbb/offset_manager.go#L251-L277

So you can check for any errors in your range loop on the consumer Errors channel and attempt to log or handle offset commit ones there
