### ISSUE TITLE
Some questions about asyncProducer.input

### ISSUE THREAD

**Issue by xqzhang2015** [IBM/sarama#1919]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.0 | 2.12-0.10.2.1 | go1.15.3 linux/amd64 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	conf := sarama.NewConfig()

	conf.ClientID = cfg.ID
	conf.ChannelBufferSize = 512
	conf.Net.MaxOpenRequests = 1000000
	conf.Net.SASL.Enable = false
	conf.Producer.MaxMessageBytes = 1000000
	conf.Producer.RequiredAcks = sarama.WaitForAll
	conf.Producer.Timeout = 30 * time.Second
	conf.Producer.Partitioner = newHashPartitioner
	conf.Producer.Compression = sarama.CompressionGZIP
	conf.Producer.Return.Successes = true
	conf.Producer.Return.Errors = true
	conf.Producer.Flush.Bytes = 0
	conf.Producer.Flush.Messages = 200
	conf.Producer.Flush.Frequency = time.Duration(1000) * time.Millisecond
	conf.Producer.Flush.MaxMessages = 100000
	conf.Producer.Retry.Max = 6
	conf.Producer.Retry.Backoff = 10 * time.Second

	addrs := strings.Split(cfg.Brokers, ",")
	producer, err := sarama.NewAsyncProducer(addrs, conf)
```

##### Logs
NA

##### Problem Description

1. When concurrently sending message to async producer, partial message can't be send into the channel. I know there are multiple level channels: top-level => topic-level => partition-level, but the top-level channel asyncProducer.input has no buffer.
Should the fail be caused by that? If yes, is it expected or by design? And is there any better usage for concurrently sending messages? In my code, sending message to kafka can't block the business logic.

```go
select {
	case producer.Input() <- m:
	default:
		err = errors.New("queue_full_fail")
	}
```
2. After adding another buffered-channel before asyncProducer.input, submitting message to asyncProducer works well. Is it possible to make the asyncProducer.input with buffer?
3. Is there any proposal for my conf and creating-client code?
4. If there is one topic is blocked, like because of too many messages, all topics in the same asyncProducer will be blocked, right? Is it expected? Any proposal for the multiple topics use case? Any further improvement for asyncProducer?

**Comment by xqzhang2015** [comment]
@dnwe could I confirm if there is any plan for this thread?

**Comment by dnwe** [comment]
@xqzhang2015 sorry for the slow reply, this old issue must have slipped through the cracks

The AsyncProducer top-level is unbuffered, but the per-topic input channels are buffered. So in your config you've set `conf.ChannelBufferSize = 512` which means the AsyncProducer will have a buffered channel of size 512 for the Input channel for each topic:

https://github.com/IBM/sarama/blob/24f12491720ed7974c2f131dae192040f6722e86/async_producer.go#L485-L486

So if one of these topic channels is filling up and then the AsyncProducer dispatcher func is blocking attempting to direct a message to one of those topic channels then the dispatcher won't be reading from the top-level Input and because of your `select { ... }` around your write to the Input channel, it will execute the default case because it couldn't immediately write to the channel.

Do you need to have that non-blocking behaviour for your call to input, or could you change the `default:` queue_full_fail case to be some `time.After` timeout? If not, then bumping ChannelBufferSize to more than 512 to permit more in-memory storage would be your solution

**Comment by xqzhang2015** [comment]
@dnwe thanks for your reply so much.

_`Do you need to have that non-blocking behavior for your call to input, or could you change the default: queue_full_fail case to be some time.After timeout?`_ 

Yes, we need the non-blocking behavior.

_`time.After`_ timeout is a graceful approach. But it will new timer when producing each message, which seems not efficient(performance view, right?).
