### ISSUE TITLE
[Feature request] Support for MSK & IAM integration

### ISSUE THREAD

**Issue by bpuertolas** [IBM/sarama#1985]
**Is your feature request related to a problem? Please describe.**
Recently, AWS released an integration between Amazon MSK (Amazon Managed Stream for Kafka) and IAM (Identity & Access Management). There is an example of this [implementation](https://aws.amazon.com/blogs/big-data/securing-apache-kafka-is-easy-and-familiar-with-iam-access-control-for-amazon-msk/) but they're using a java client and a library named [aws-msk-iam-auth](https://github.com/aws/aws-msk-iam-auth) in order to match IAM security.

**Describe the solution you'd like**
Would like to fully support this new integration.

**Additional context**
Currently, the only security measures that can be added to a Amazon MSK cluster is by protecting it with security groups or TLS. These options are full deny or full allow, there's no way to define a set of access per topic. This new integration with IAM allow this.

**Comment by gunturaf** [comment]
There's implementation reference for AWS_MSK_IAM at `franz-go` in this example https://github.com/twmb/franz-go/tree/master/examples/sasl/aws_msk_iam , I think it's a great addition to Sarama because downstream projects such as [otel-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) and [Benthos](https://github.com/Jeffail/benthos) uses Sarama as their underlying Kafka client, if Sarama supports this then the other projects will benefit too.

Can we _sort of_ copy-pasta your AWS_MSK_IAM code in `franz-go` to achieve this in Sarama, @twmb ?

**Comment by cmaher** [comment]
[kafka-go now has another reference implementation](https://github.com/segmentio/kafka-go/blob/main/sasl/aws_msk_iam/msk_iam.go), which uses the aws-sdk to perform the signing, if the maintainers prefer that.

**Comment by twmb** [comment]
opentelemetry managed to work around this without any changes to sarama. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/kafkaexporter/authentication.go#L127

**Comment by MovieStoreGuy** [comment]
This needs to be added to the main project, the otel contribution written by me is currently flawed since sarama does validation checks on the auth mechanism used. 

This should be a simple as taking the current version in otel and making it part of the main library.

**Comment by tooptoop4** [comment]
bump

**Comment by bpalermo** [comment]
@MovieStoreGuy any progress on this?

**Comment by dtjm** [comment]
AWS has released a solution here https://github.com/aws/aws-msk-iam-sasl-signer-go
