### ISSUE TITLE
alibabacloud recommends against using Sarama?

### ISSUE THREAD

**Issue by KeenCN** [IBM/sarama#2036]
I saw from alibabacloud that Sarama library is not recommended by them. Do we have a repair plan for these three problems?

source:
https://www.alibabacloud.com/help/faq-detail/266782.htm

Quote：

> The following known problems exist with the Go client that is developed with the Sarama library:
> 
> 1. When a partition is added to a topic, the Go client developed with the Sarama library cannot detect the new partition or consume messages from the partition. Only after the client is restarted, it can consume messages from the new partition.
> 
> 2. When the client subscribes to more than two topics at the same time, the client may fail to consume messages from some partitions.
> 
> 3. If the policy for resetting consumer offsets of the Go client developed with the Sarama library is set to Oldest(earliest), the client may start to consume messages from the earliest offset when the client breaks down or the broker version is upgraded. This is because the out_of_range class is implemented in the client.

**Comment by dnwe** [comment]
@KeenCN this is the first time I have seen this document, and I'd have to search to see if whoever is responsible for it ever raised any issues for these problems, but it seems somewhat out-of-date and it's unclear for the other two what is being described.

RE: 1., I believe that issue was fixed in Version 1.24.1 (2019-10-31) under #1525 

RE: 2, I'm not sure what issue they are referring to here, I'm assuming they saw some behaviour where the fairness of message consumption between topics wasn't as balanced as they would like? It's not something I've personally seen before, but we could investigate if someone can put together a functional test or example that reproduces whatever they were seeing.

RE: 3., again I'm not sure exactly what they are describing here. If the broker is restarted and truncates a partition such that the consumer gets an out of range error, then the broker consumer will stop due to the ErrOffsetOutOfRange and if `Consumer.Return.Errors` is set then it will return that error to the user to decide what to do. Then when they reconnect the offset reset configuration should only be used in the event that their consumer group didn't have a committed offset on the __consumer_offsets topic that is still valid post-truncation.

**Comment by onlyice** [comment]
I can confirm that Sarama can detect new partition(s). But it happened after a metadata refresh, which by default happened in a 10 minutes interval. Could be the cause of the misunderstanding of the first issue.

**Comment by erenming** [comment]
> I can confirm that Sarama can detect new partition(s). But it happened after a metadata refresh, which by default is by a **10 minutes interval**. Could be the cause of the misunderstanding of the first issue.

Yes, you're right. And we should notice, in that case(eg. detect new partitions), the session will exit, so users should always retry the Consume method. [Here explained detailly](https://github.com/Shopify/sarama/issues/1685#issuecomment-652537977)

**Comment by cheaster062211** [comment]
> > 我可以确认 Sarama 可以检测到新分区。但它发生在元数据刷新之后，默认情况下**间隔为 10 分钟**。可能是对第一个问题的误解的原因。
> 
> 你是对的。我们应该注意到，在那种情况下（例如检测到新分区），会话将退出，因此用户应该始终重试 Consume 方法。[这里有详细解释](https://github.com/Shopify/sarama/issues/1685#issuecomment-652537977)
![image](https://user-images.githubusercontent.com/28662473/228735843-f099049b-e858-42c1-afd4-bd0cb280d02d.png)
When this oldTopicToPartitionNum already changed , and subsequent checks based on the changed number, then cannot trigger the rebalance

**Comment by cheaster062211** [comment]
> @KeenCN this is the first time I have seen this document, and I'd have to search to see if whoever is responsible for it ever raised any issues for these problems, but it seems somewhat out-of-date and it's unclear for the other two what is being described.
> 
> RE: 1., I believe that issue was fixed in Version 1.24.1 (2019-10-31) under #1525
> 
> RE: 2, I'm not sure what issue they are referring to here, I'm assuming they saw some behaviour where the fairness of message consumption between topics wasn't as balanced as they would like? It's not something I've personally seen before, but we could investigate if someone can put together a functional test or example that reproduces whatever they were seeing.
> 
> RE: 3., again I'm not sure exactly what they are describing here. If the broker is restarted and truncates a partition such that the consumer gets an out of range error, then the broker consumer will stop due to the ErrOffsetOutOfRange and if `Consumer.Return.Errors` is set then it will return that error to the user to decide what to do. Then when they reconnect the offset reset configuration should only be used in the event that their consumer group didn't have a committed offset on the __consumer_offsets topic that is still valid post-truncation.

When this oldTopicToPartitionNum already changed , and subsequent checks based on the changed number, then cannot trigger the rebalance

**Comment by dnwe** [comment]
PR https://github.com/IBM/sarama/pull/2563 is also relevant here

**Comment by nick887** [comment]
the 2 happens to me, we use sarama consumer group, 1 groupID and 4 topic

we have 3 pods, each pod have the same config for consumerGroup & topic

When deploying, we often encounter that a certain topic cannot be consumed normally.

the kafka meta shows that this topic doesn't have any consumer, and we think there is no exit from Consume function, the sarama just stuck

another question is that when we deploy service, it takes a long time to wait for the Consume function exit, even if the context is canceled, we doubt that this may be one of the reasons for not consume

is there any help, i will be grateful
