### ISSUE TITLE
Not able to find the consumer setting max.poll.records

### ISSUE THREAD

**Issue by sameershah25** [IBM/sarama#2049]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.26.4 | 2.2.0  |  1.14 |

##### Problem Description
How to set the "max.poll.records" https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_max.poll.records which is available in java kafka client library?

**Comment by dnwe** [comment]
Unlike the Java client, Sarama doesn't have an equivalent of `max.poll.records` because we don't have a sync consumer, we only provide a streaming consumer with a `Messages` channel that you read from.

Note that even in the Java client, `max.poll.records` simple influences the maximum number of records returned in a single call to the poll() method. It does not change the protocol or the underlying fetching behaviour with Kafka, the client just caches records it has received in memory for when you next call `poll()`

**Comment by craiglservin** [comment]
It does however impact consumer rebalances.

It's a lot easier in human terms to adjust the timeouts against a number of messages than it is against a buffer size.   Particularly if the messages are json and producer compression is enabled there can be a wild swing in the number of messages fetched by the consumer.

I realize that under the hood it is fetching base on buffer sizes and `max.poll.records`  just caused another fetch, but from the perspective of the consumer developer it is a lot more intuitive.

**Comment by sab13c** [comment]
@craiglservin 
I am in a similar predicament. Where you able to get a solution for this?

**Comment by dnwe** [comment]
From a consumer's perspective, it's a combination of ChannelBufferSize https://github.com/IBM/sarama/blob/05cb9fa28349a2092fb03a0f781455c9a383c9e3/config.go#L478-L482 and MaxProcessingTime https://github.com/IBM/sarama/blob/05cb9fa28349a2092fb03a0f781455c9a383c9e3/config.go#L391-L408 which combine in the partition consumer's expiry ticker https://github.com/IBM/sarama/blob/05cb9fa28349a2092fb03a0f781455c9a383c9e3/consumer.go#L568-L570

Note that there is a partition consumer for each topic partition that your client was assigned within the consumer group. With the defaults the client will buffer up to 256 messages for the partition so you need to be processing the incoming messages for each topic partition fast enough so that buffer doesn't fill and block for more than 100ms
