### ISSUE TITLE
Using the scram client example in an open source project

### ISSUE THREAD

**Issue by ppatierno** [IBM/sarama#2055]
Hello,
as one of the maintainers of the Strimzi project, we have a component [1] using the Sarama library and I would like to use the SCRAM-SHA support.
I noticed that even other people/projects just used the example that Sarama provides as scram client [2] and I would like to do the same because it works out of box for our use case too.
My concern is what kind of reference you would like to have in our repository if I copy/paste your example code there.
Should I just refer with a comment to your example file?
@dnwe any concerns about it? I would like just to be sure to provide credits to Sarama contributors in the right way. Thanks!

[1] https://github.com/strimzi/strimzi-canary
[2] https://github.com/Shopify/sarama/blob/main/examples/sasl_scram_client/scram_client.go

**Comment by dnwe** [comment]
Hey Paolo. It probably needs someone from Spotify to comment really as they own Sarama as an entity rather than me. 

I’m assuming the examples are governed by the MIT license, so the safest/simplest option if you’re taking the sample scram_client.go as-is is probably just to put a full copy of https://raw.githubusercontent.com/Shopify/sarama/main/LICENSE at the top of the file in comments.

**Comment by ppatierno** [comment]
@dnwe thanks for the quick answer! Do you know who we can tag here from Spotify for having confirmation that your proposal looks ok to them?

**Comment by dnwe** [comment]
Closing as resolved
