### ISSUE TITLE
Error while performing GSSAPI Kerberos Authentication: EOF

### ISSUE THREAD

**Issue by slivewo** [IBM/sarama#2258]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.29.0 | v1.0.0 | 1.18 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` 
kc.Net.SASL.Mechanism = sarama.SASLTypeGSSAPI
kc.Net.SASL.Enable = true
kc.Net.SASL.GSSAPI.ServiceName = config.KafkaServiceName
kc.Net.SASL.GSSAPI.Realm = config.KafkaRealm
kc.Net.SASL.GSSAPI.Username = config.KafkaPrincipal
kc.Net.SASL.GSSAPI.AuthType = sarama.KRB5_KEYTAB_AUTH
kc.Net.SASL.GSSAPI.KeyTabPath = config.KafkaKeytab
kc.Net.SASL.GSSAPI.KerberosConfigPath = config.KafkaCrb5conf
kc.Version = sarama.V1_0_0_0

realm: HDP.COM
principal: homegateway
keytab: homegateway.keytab
crb5conf: /etc/krb5.conf
serviceName: krbtgt
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
[sarama] 2022/06/21 18:36:55 Error while performing GSSAPI Kerberos Authentication: EOF
[sarama] 2022/06/21 18:36:55 Closed connection to broker 172.17.37.81:9092
[sarama] 2022/06/21 18:36:55 client/metadata got error from broker -1 while fetching metadata: EOF
[sarama] 2022/06/21 18:36:55 client/metadata no available broker to send metadata request to
[sarama] 2022/06/21 18:36:55 client/brokers resurrecting 1 dead seed brokers
[sarama] 2022/06/21 18:36:55 Closing Client
```

</p>
</details>

##### Problem Description
```
kerberos login returns normal authentication information as it should be successful.
But the encapsulation header seems to be wrong. The length of the data field returned by krbAuth readPackage is 0. 
```

**Comment by kmetaxas** [comment]
I'm running in to the same issue.
It started happening after upgrading from Confluent platform 6.2 to 7.3 (from KAfka 2.8 to 3.3 )
It seems to be related a combination of both Kerberos auth + Kafka version. If i use another authentication method (Oauthbearer for example) i do not get any errors. If i use CP 6.2 (kafka 2.8) this goes away as well.

I also noticed that the error also happens when i tried switching to franz-go. 
At this point, all  i can think of is some detail in SASL + gssapi changing that go implementations don't support.

Java + librdkafka based applications do not have this issue and connect normally with GSSAPI.

**Comment by dnwe** [comment]
Hmm that’s interesting

**Comment by dnwe** [comment]
We should really add a functional test that enables gssapi and does a simple auth and roundtrip
