### ISSUE TITLE
[Question] How does SendMessages() work when some messages in the batch failed?

### ISSUE THREAD

**Issue by kpeu3i** [IBM/sarama#2306]
Let's imagine I'm sending 5 messages (1, 2, 3, 4, 5) using `SendMessages` method. 
According to the documentation:
```
	// SendMessages produces a given set of messages and returns only when all
	// messages in the set have either succeeded or failed. Note that messages
	// can succeed and fail individually; if some succeed and some fail,
	// SendMessages will return an error.
	SendMessages(msgs []*ProducerMessage) error
```

some messages can fail individually.

Is it possible that the messages in the middle of the batch will fail, but the remaining will be sent successfully?
```
(1 - OK, 2 - OK, 3 - FAILED, 4 - FAILED, 5 - OK)
```
or Sarama stops sending the messages on the first error in the batch?
```
(1 - OK, 2 - OK)
```

**Comment by petromir** [comment]
@dnwe Could you please provide an answer to the above?

**Comment by petromir** [comment]
Not sure if it already resolved, but we switched to another library because of this issue and this project seems like abandoned.

**Comment by dnwe** [comment]
To be clear on the terminology, this is a _set_ of messages, not a _batch_ of messages, and yes individual messages within this Set might fail and "later" ones might pass.

The messages you pass to the sync producer's SendMessages at the top-level can be for any number of different topics and depending on the partitioner and the number of partitions on that topic, can require connections and ProduceRequests to be sent to any number of brokers in order to send the set, so it all depends on how the messages end up in batches of ProduceRequests

Kafka itself only guarantees ordering on a given topic-partition
