### ISSUE TITLE
 error: kafka: client has run out of available brokers to talk to: EOF

### ISSUE THREAD

**Issue by lianglinhuan** [IBM/sarama#2325]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.36.0 |2.8.1  |1.18  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

**Comment by lianglinhuan** [comment]
I don't know why this error is reported, can you ask a professional to answer it? Honored

**Comment by polin-x** [comment]
hello, I have this problem too, did you solve it?

**Comment by vivek-rao-1985** [comment]
same problem here

**Comment by Juandavi1** [comment]
Hi ! I achieve it ! 
I was working with test containers and I was shutting down the kafka container before the test is over.

Now it works ! 

Thanks

**Comment by sN0wpeak** [comment]
Is there any recent progress on this issue?

**Comment by cloverland** [comment]
If I set SASL here, it is probably because the SASL certification has not passed

**Comment by dnwe** [comment]
"client has run out of available brokers to talk to" is a common error if there is a misconfiguration in protocol Version or SASL / SSL etc., but it needs the full logger output to diagnose

I'm going to close this old issue as the original post didn't include that and people are stumbling upon this whilst search for their own problem, but it would be better to raise a separate issue so that we can diagnose each case individually

**Comment by javaDer** [comment]
Hello everyone, this is how I solved this problem:
for reference only:
I downgraded sarama to v1.19.0. The code is as follows:
go get github.com/Shopify/sarama@v1.19.0
It will work normally
