### ISSUE TITLE
partitionProducer newHighWatermark panic in v1.33.0

### ISSUE THREAD

**Issue by ajeyprasad** [IBM/sarama#2650]
##### Description

Facing this panic when kafka is stopped while sending the messages.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1008bd7c8]

goroutine 103 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0x140001b2840, 0x1)
	/Users/test/go/pkg/mod/github.com/!shopify/sarama@v1.33.0/async_producer.go:620 +0x2e8
github.com/Shopify/sarama.(*partitionProducer).dispatch(0x140001b2840)
	/Users/test/go/pkg/mod/github.com/!shopify/sarama@v1.33.0/async_producer.go:564 +0x5c4
github.com/Shopify/sarama.withRecover(0x140003420d0)
	/Users/test/go/pkg/mod/github.com/!shopify/sarama@v1.33.0/utils.go:43 +0x4c
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
	/Users/test/go/pkg/mod/github.com/!shopify/sarama@v1.33.0/async_producer.go:515 +0x2f8
```

##### Versions

| Sarama | Kafka | Go  |  OS |
| ------ | ----- | --- | ---- |
|   v1.33.0    |    3.4.0   |  1.18   | MAC M1 Chip |

**Comment by dnwe** [comment]
@ajeyprasad this sounds like a duplicate of https://github.com/IBM/sarama/issues/2322 which was fixed in [v1.38.0](https://github.com/IBM/sarama/releases/tag/v1.38.0) via https://github.com/IBM/sarama/pull/2387

I'd recommend updating to the github.com/IBM/sarama import path and pulling in the latest version of [v1.41.2](https://github.com/IBM/sarama/releases/tag/v1.41.2)
