### ISSUE TITLE
Kafka client panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by CharlesCheung96** [IBM/sarama#2681]
##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|     1.38.1   |   kafka_2.11-1.1.1    |   go1.19.9  |

##### Configuration

```go

```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```
goroutine 54946562 [running]:
github.com/eapache/go-resiliency/breaker.(*Breaker).doWork(0xc0114a373b?, 0x0, 0x0?)
github.com/eapache/go-resiliency/breaker.(*Breaker).Run(...)
github.com/eapache/go-resiliency@v1.3.0/breaker/breaker/breeaker.go:100 +0xa5
github.com/eapache/go-resiliency@v1.3.0/breaker/breakergo:55
github.com/Shopify/sarama@v1.38.1/async_producer.go:755 +0x54
github.com/Shopify/sarama@v1.38.1/async_producer.go0:618 +0x35
github.com/Shopify/sarama@v1.38.1/async_producer.go:688 +0x570
github.com/Shopify/sarama@v1.38.1/utils.go:43 +0x3e 
github.com/Shopify/sarama.(*partitionProducer).updateLeader(x3a3ํ76bc?)
github.com/Shopify/sarama.(*partitionProducer).updateLeaderIfBrokerProducerIsNil(0xc39560a240, 0xc064f11180)
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc39560a240)
github.com/Shopify/sarama.withRecover(0xc0a540cf98?)
created
by github.com/Shopify/sarama.(*asyncProducer).newPaartitionProducer
github.com/Shopify/sarama@v1.38.1/async producer.go:599 +0x1ea

```

</p>
</details>

**Comment by dnwe** [comment]
Unfortunately because of the go-resiliency wrapper here recovering and then rethrowing the panic, we lose the original stack trace info that indicates where the assignment to a nil map occurred. I'd _guess_ that it might be around `github.com/Shopify/sarama.(*client).registerBroker` as that is where we've seen a panic (such as https://github.com/IBM/sarama/issues/1920) in the past

However, v1.38.1 is quite old now, and we have made numerous improvements. Would you be able to look at upgrading your app to use [github.com/IBM/sarama@v1.42.0](https://github.com/IBM/sarama/releases/tag/v1.42.0)?

**Comment by dnwe** [comment]
Closing, assumed as fixed — feel free to re-open if you still think this is an issue

**Comment by kennytm** [comment]
For record we have encountered the same stack trace using `sarama 1.41.2`

```
panic: assignment to entry in nil map

goroutine 627227 [running]:
github.com/eapache/go-resiliency/breaker.(*Breaker).doWork(0x4d03715?, 0x0, 0x43ec4e?)
	github.com/eapache/go-resiliency@v1.4.0/breaker/breaker.go:100 +0x96
github.com/eapache/go-resiliency/breaker.(*Breaker).Run(...)
	github.com/eapache/go-resiliency@v1.4.0/breaker/breaker.go:55
github.com/IBM/sarama.(*partitionProducer).updateLeader(0x256785e208ad37?)
	github.com/IBM/sarama@v1.41.2/async_producer.go:756 +0x4f
github.com/IBM/sarama.(*partitionProducer).updateLeaderIfBrokerProducerIsNil(0xc02335f5c0, 0xc020f82500)
	github.com/IBM/sarama@v1.41.2/async_producer.go:619 +0x2c
github.com/IBM/sarama.(*partitionProducer).dispatch(0xc02335f5c0)
	github.com/IBM/sarama@v1.41.2/async_producer.go:689 +0x537
github.com/IBM/sarama.withRecover(0xc005398f98?)
	github.com/IBM/sarama@v1.41.2/utils.go:43 +0x33
created by github.com/IBM/sarama.(*asyncProducer).newPartitionProducer in goroutine 626992
	github.com/IBM/sarama@v1.41.2/async_producer.go:600 +0x1df
```

The log suggested it happened [during `(sarama.AsyncProducer).Close()`](https://github.com/IBM/sarama/blob/v1.41.2/async_producer.go#L358).

We are also in process of upgrading to `sarama 1.45.0`.

**Comment by kennytm** [comment]
I think it is a race condition between the application closing the AsyncProducer and somewhere creating a new PartitionProducer.

Anyway, we are already migrating to `sarama 1.45.0`, but as you mentioned there is no proper stacktrace because of `go-resiliency`, will this loss of debug info be fixed on the newest version? Just in case it happened again.

**Comment by puellanivis** [comment]
It would seem that `go-resiliency` still on their trunk branch is catching and rethrowing the panic. ☹
