### ISSUE TITLE
ClientID regex is too restrictive.

### ISSUE THREAD

**Issue by alexhein** [IBM/sarama#2697]
##### Description
The sarama client allows to set the client.id in the (producer) configuration. It is not uncommon to use symbols like '|' in the client ID string. The regex does not allow this, however. See https://github.com/IBM/sarama/blob/82f0e48b0e2b6dfefc3088fe5e45195f6cc461d8/config.go#L18

**Comment by dnwe** [comment]
@alexhein yes that's interesting, I have seen for example mirror connectors use `|` in their generated clientIDs these days [here](https://github.com/apache/kafka/blob/7bdd1a015e2a91192c0ea07b39bd4d9195472763/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorConnectorConfig.java#L240-L244)

I believe the original validation regex was based on the one that existed in the Java clients pre-1.0.0 but [KIP-190](https://cwiki.apache.org/confluence/display/KAFKA/KIP-190%3A+Handle+client-ids+consistently+between+clients+and+brokers) removed the client-side validation because instead the brokers were updated to be able to cope with any clientID and sanitize it before using it in metrics

**Comment by alexhein** [comment]
@dnwe  Thank you for pointing me to the KIP, I was not aware of that.
