### ISSUE TITLE
Kafka as a work queue

### ISSUE THREAD

**Issue by vunguyen1989** [IBM/sarama#2742]
Hi,

I was working with RabbitMq, using it as a task queue. It seems working well at the beginning but the traffic comes then having issues. I want to use Kafka for my project instead of RabbitMq.

I have a hint on using `shared consumer group` for making Kafka as a task queue; I have been already searching for some hours but no luck. 

Can you give me a guide on this?
A code example will be highly appreciated.

Thanks much

**Comment by dnwe** [comment]
Do your tasks have ordering requirements or are they just isolated units of work? Today, this is likely to be much easier to achieve using a queue provided via a message broker, rather than using a partitioned kafka topic with a shared consumer group. RabbitMQ has a feature set which is tailored for task queuing so would be a reasonable choice for your use case

**Comment by vunguyen1989** [comment]
Hi @dnwe, the tasks have some strict requirements. Kafka is one of them.
Thanks for the response.
