### ISSUE TITLE
Why not refresh metadata when got ErrNotLeaderForPartition

### ISSUE THREAD

**Issue by ForeverSRC** [IBM/sarama#2760]
We got some `ErrNotLeaderForPartition` error after retrying for 3 times, I wonder why the producer doesn't refresh metadata when got that error.
https://github.com/IBM/sarama/blob/d9abf3cfb14d41fbc059d0f36195603000b1aad2/async_producer.go#L1121-L1126

**Comment by dnwe** [comment]
@ForeverSRC thanks for raising, a good question!

Refreshing metadata in the producer retry case was brought in as part of the Idempotent producer changes, but it's not clear that this refresh _needs_ to be gated for idempotent-only retries

**Comment by dnwe** [comment]
@ForeverSRC having updated my memory of this after re-reading the code, any retriabe error for a given broker producer should cause it to 'abandon' the broker, do a metadata refresh on the assumption it needs use a different broker producer because the topicpartition has moved:

https://github.com/IBM/sarama/blob/5f63a84f47c39bf08a1c276f1f6b5f1d754e9fc3/async_producer.go#L710-L724

You'd see this in sarama logger output as (e.g.,):
13:45:16.866724 producer/leader/my_topic/0 state change to [retrying-1]
13:45:16.866735 producer/leader/my_topic/0 abandoning broker 2

**Comment by ForeverSRC** [comment]
In my use case we got three `ErrNotLeaderForPartition` errors because the retry times is 3 and the interval is 100ms, so I'm not sure if the abandon logic works or not.
