### ISSUE TITLE
req.AddBlock not enough arguments in call, how could fix it ?

### ISSUE THREAD

**Issue by gopherhiro** [IBM/sarama#2821]
# github.com/bsm/sarama-cluster
../../pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/consumer.go:238:63: not enough arguments in call to req.AddBlock
	have (string, int32, int64, number, string)
	want (string, int32, int64, int32, int64, string)

**Comment by dnwe** [comment]
So I'm guessing you're migrating a legacy application here?

Historically [bsm/sarama-cluster](https://github.com/bsm/sarama-cluster) was a wrapper package around sarama when it didn't originally have its own consumer group implementation. That wrapper  has been deprecated since v1.19.0 of Sarama (which came out in 2018) added its own consumer group capability. See https://github.com/IBM/sarama/blob/main/examples/consumergroup/main.go for an example of its usage

**Comment by gopherhiro** [comment]
Oh, I see. Thank you very much. I downgraded the version of the sarama package to v1.24.0 Then, it works. Trying to understand why sarama-cluster is not maintained anymore?

**Comment by dnwe** [comment]
As mentioned above - sarama-cluster was a temporary third party module that was released after the Kafka server started to support consumer groups. At that time sarama itself only supported the legacy consumer model. However, once Sarama itself had added support for consumer groups there was no longer a need for that third party module to exist anymore

**Comment by gopherhiro** [comment]
Does Sarama already support consumer groups?

**Comment by gopherhiro** [comment]
I understand, thank you very much for your answer and I wish you all the best!

**Comment by dnwe** [comment]
👍🏻 no worries
