### ISSUE TITLE
gopkg import with the mocks subpackage

### ISSUE THREAD

**Issue by aaronkavlie-wf** [IBM/sarama#497]
The `mocks` subpackage imports `github.com/Shopify/sarama`. The README suggests using `gopkg.in`  (which github.com/wvanbergen/kafka does), but it leads to conflicts when using mocks like so:

```
cannot use "gopkg.in/Shopify/sarama.v1".NewConfig() (type *"gopkg.in/Shopify/sarama.v1".Config) as type *"github.com/Shopify/sarama".Config in argument to mocks.NewSyncProducer
```

**Comment by eapache** [comment]
Hmm, cc @wvanbergen this is actually kind of annoying; if we switch the import paths for the mocks to use gopkg, then it will break for anybody using master directly (of which there are at least a few)...

**Comment by eapache** [comment]
It might be possible to work around this via https://golang.org/doc/go1.4#canonicalimports? I'm not 100% sure, I think it depends on exactly how gopkg.in proxies the repo.

**Comment by wvanbergen** [comment]
/me suppresses rant about the shitty package management tooling in go.

I don't know how that would work. Based on those docs, adding a canonical import path will just make one of the two locations fail. `gopkg.in` would have to do some rewriting as part of the proxying for it to work, but that is kind of against the idea of a *canonical* import path.

**Comment by wvanbergen** [comment]
maybe we can just use a relative import? `import './mocks'`

**Comment by eapache** [comment]
Relative imports break `go get` and a bunch of other things, I think... maybe worth trying though to see?

**Comment by fgrosse** [comment]
Unfortunately it seems like there is still no real solution to this issue yet. Here are my thoughts:

Did you consider moving the mocks into the `github.com/Shopify/sarama` package directly? There are no extra dependencies this would introduce there and just simplify the code and imports. This change could be introduced under a new major version (i.e. `gopkg.in/Shopify/sarama.v2`) since moving the mocks package obviously breaks BC.

Of course this would break all users that import the github repository directly but if this is actually an issue for the library then I wonder why you are using `gopkg.in` in the first place. Maybe the actual solution should be to stop advertising the usage of `gopkg.in` alltogether?

**Comment by varun06** [comment]
I wonder if this is still an issue with go modules?

**Comment by ograycode** [comment]
Yes, I believe so @varun06

**Comment by dnwe** [comment]
@bai since Sarama requires go modules for some time now, is there any benefit to still using gopkg.in anymore? Perhaps we should enable the canonical import path of github.com/Shopify/sarama everywhere?

**Comment by bai** [comment]
@dnwe I'm 👍for this change.

**Comment by dnwe** [comment]
Closing this as outdated, please re-open if you still think there is something we can do here
